name: Deploy to Server

on:
  push:
    branches: [main]
    paths:
      - 'flowming/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean npm cache and files
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --workspace=flowming

      - name: Run tests
        run: npm test --workspace=flowming

      - name: Build project
        run: npm run build --workspace=flowming

      - name: Deploy files
        run: |
          rm -rf /var/www/flow-diagram/*
          cp -a flowming/dist/* /var/www/flow-diagram/
          chown -R github-runner:www-data /var/www/flow-diagram

      - name: Restart server
        run: |
          systemctl restart nginx

      - name: Clean up
        run: |
          rm -rf flowming/dist
          rm -rf node_modules
          rm -rf flowming/node_modules
          rm -rf y-webrtc-server/node_modules
          rm -f package-lock.json
