name: Test

on:
  pull_request:
    branches: [main]
    paths:
      - 'flowming/**'
      - 'y-webrtc-server/**'
      - '.github/workflows/test.yml'
  push:
    branches: [main]
    paths:
      - 'flowming/**'
      - 'y-webrtc-server/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      #- name: Run linting
      #  run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project (verify build works)
        run: npm run build 